package com.lyeeedar.Board.CompletionCondition

import com.badlogic.gdx.scenes.scene2d.ui.Table
import com.lyeeedar.Board.Grid
import com.lyeeedar.Util.XmlData

/**
 * Created by Philip on 07-Aug-16.
 */

class CompletionConditionNoneData : AbstractCompletionConditionData()
{
	override val classID: String = "None"

	override fun load(xmlData: XmlData)
	{
	/* Autogenerated method contents. Do not modify. */
		super.load(xmlData)
	}
}

class CompletionConditionNone(data: CompletionConditionNoneData) : AbstractCompletionCondition<CompletionConditionNoneData>(data)
{
	override fun createTable(grid: Grid): Table = Table()

	override fun getDescription(grid: Grid): Table = Table()

	override fun attachHandlers(grid: Grid)
	{

	}

	override fun isCompleted(): Boolean = false
}