package com.lyeeedar.Board.CompletionCondition

import com.badlogic.gdx.scenes.scene2d.ui.Label
import com.badlogic.gdx.scenes.scene2d.ui.Table
import com.lyeeedar.Board.Grid
import com.lyeeedar.Board.Tile
import com.lyeeedar.Components.Entity
import com.lyeeedar.Game.Global
import com.lyeeedar.UI.SpriteWidget
import com.lyeeedar.UI.Tutorial
import com.lyeeedar.Util.*

@DataClass(name = "Plate")
class CompletionConditionPlateData : AbstractCompletionConditionData()
{
	override val classID: String = "Plate"

	override fun load(xmlData: XmlData)
	{
	/* Autogenerated method contents. Do not modify. */
		super.load(xmlData)
	}
}

class CompletionConditionPlate(data: CompletionConditionPlateData) : AbstractCompletionCondition<CompletionConditionPlateData>(data)
{
	var remaining = -1
	lateinit var label: Label

	override fun attachHandlers(grid: Grid)
	{
		remaining = grid.grid.count(Tile::hasPlate)

		grid.onTurn += {
			remaining = grid.grid.count(Tile::hasPlate)
			label.setText(" x $remaining")
			HandlerAction.KeepAttached
		}

		grid.onPop += fun (orb: Entity, delay: Float ) : HandlerAction {
			remaining = grid.grid.count(Tile::hasPlate)
			label.setText(" x $remaining")

			return HandlerAction.KeepAttached
		}

		if (!Global.resolveInstantly)
		{
			Future.call(
				{
					val tutorial = Tutorial("PlateComplete")
					tutorial.addPopup(Localisation.getText("completioncondition.plate.tutorial", "UI"), label)
					tutorial.show()
				}, 0.5f)
		}
	}

	override fun isCompleted(): Boolean = remaining == 0

	override fun createTable(grid: Grid): Table
	{
		val table = Table()

		val sprite = grid.level.theme.data.plate.copy()
		label = Label(" x $remaining", Statics.skin)

		table.add(SpriteWidget(sprite, 24f, 24f))
		table.add(label)

		return table
	}

	override fun getDescription(grid: Grid): Table
	{
		val table = Table()

		table.add(Label(Localisation.getText("completioncondition.plate.description", "UI") + " $remaining ", Statics.skin))
		table.add(SpriteWidget(grid.level.theme.data.plate.copy(), 24f, 24f))

		return table
	}
}