name: CI

on: [push, pull_request]
jobs:
  test:
    runs-on: macOS-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master
      with:
        path: Game

    - name: Checkout submodules
      working-directory: Game
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --rebase -j 8

    - name: Checkout private
      uses: actions/checkout@master
      with:
        repository: Lyeeedar/PrivateStuff
        token: ${{ secrets.PRIVATESTUFF_ACCESS_TOKEN }}
        path: PrivateStuff

    - name: Hash project contents
      run: echo "::set-env name=PROJECT_HASH::${{ hashFiles('**/*.kt') }}-${{ hashFiles('**/*.xml') }}-${{ hashFiles('**/*.gradle') }}"

    - name: Restore gradle cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ env.PROJECT_HASH }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Restore resource cache
      uses: actions/cache@v1
      with:
        path: Game/android/caches
        key: resourceCache-${{ env.PROJECT_HASH }}
        restore-keys: resourceCache-

    - name: Make gradlew executable
      working-directory: Game
      run: chmod +x ./gradlew

    - name: Build Desktop
      working-directory: Game
      run: ./gradlew :desktop:build

    - name: Build Android
      working-directory: Game
      run: ./gradlew :android:assembleDebug

    - name: Build Resources
      working-directory: Game
      run: ./gradlew :headless:compileResources

    - name: Run Tests
      working-directory: Game
      run: ./gradlew :headless:testResources

 #   - name: Run Game Loop Test
 #     uses: reactivecircus/android-emulator-runner@v2
 #     with:
 #       api-level: 28
 #       script: |
 #         adb install Game/android/build/outputs/apk/debug/android-debug.apk
 #         adb shell am start -a com.google.intent.action.TEST_LOOP -n com.lyeeedar.MatchDungeon/com.lyeeedar.AndroidLauncher
 #         // somehow figure out how to sleep until the loop completes