name: CI

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        path: MatchDungeon
    
    - name: Checkout submodules
      working-directory: MatchDungeon
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --rebase -j 8
  
    - name: Checkout private
      uses: actions/checkout@master
      with:
        repository: Lyeeedar/PrivateStuff
        token: ${{ secrets.PRIVATESTUFF_ACCESS_TOKEN }}
        path: PrivateStuff
  
    - name: Make gradlew executable
      working-directory: MatchDungeon
      run: chmod +x ./gradlew
      
    - name: Build Desktop
      working-directory: MatchDungeon
      run: ./gradlew :desktop:build
      
    - name: Build Android
      working-directory: MatchDungeon
      run: ./gradlew :android:assembleDebug
    
    - name: Build Resources
      working-directory: MatchDungeon
      run: ./gradlew :headless:compileResources
