name: ReleaseToPlaystore

on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - run: git clone https://github.com/Lyeeedar/MatchDungeon /home/runner/work/MatchDungeon/MatchDungeon/MatchDungeon

    - name: Checkout submodules
      working-directory: MatchDungeon
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --rebase -j 8

    - name: Checkout private
      uses: actions/checkout@master
      with:
        repository: Lyeeedar/PrivateStuff
        token: ${{ secrets.PRIVATESTUFF_ACCESS_TOKEN }}
        path: PrivateStuff

    - run: |
        git describe --exact-match
        echo "::set-output name=status::false"
      working-directory: MatchDungeon
      id: hasChanges
      continue-on-error: true

    - name: Make gradlew executable
      working-directory: MatchDungeon
      run: chmod +x ./gradlew
      if: steps.hasChanges.outputs.status != 'false'

    - name: Bump version number
      working-directory: MatchDungeon
      run: ./gradlew :android:incrementVersion
      if: steps.hasChanges.outputs.status != 'false'

    - name: Build it
      working-directory: MatchDungeon
      run: |
        ./gradlew :headless:compileResources
        ./gradlew :headless:testResources
        ./gradlew :android:build
        ./gradlew :android:bundleRelease
      if: steps.hasChanges.outputs.status != 'false'

    - name: Setup git credentials
      working-directory: MatchDungeon
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "ReleaseToPlaystoreAction"
      if: steps.hasChanges.outputs.status != 'false'

    - name: Release to playstore
      working-directory: MatchDungeon
      run: ./gradlew :headless:releaseAndroidToPlaystore
      id: release
      if: steps.hasChanges.outputs.status != 'false'

    - name: Commit changes
      working-directory: MatchDungeon
      env:
        VERSION: ${{ steps.release.outputs.version }}
      run: |
        git commit -m"Bump version number to $VERSION and release" -a
        git tag -a releases/$VERSION -m "Release $VERSION"
      if: steps.hasChanges.outputs.status != 'false' && steps.release.outputs.status == 'Complete'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: MatchDungeon
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: steps.hasChanges.outputs.status != 'false' && steps.release.outputs.status == 'Complete'

    - name: Push tags
      uses: ad-m/github-push-action@master
      with:
        directory: MatchDungeon
        tags: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: steps.hasChanges.outputs.status != 'false' && steps.release.outputs.status == 'Complete'
