name: ReleaseToPlaystore

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - run: git clone https://github.com/Lyeeedar/MatchDungeon /home/runner/work/MatchDungeon/MatchDungeon/MatchDungeon

    - name: Checkout submodules
      working-directory: MatchDungeon
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --rebase -j 8

    - name: Checkout private
      uses: actions/checkout@master
      with:
        repository: Lyeeedar/PrivateStuff
        token: ${{ secrets.PRIVATESTUFF_ACCESS_TOKEN }}
        path: PrivateStuff

    - name: Make gradlew executable
      working-directory: MatchDungeon
      run: chmod +x ./gradlew

    - name: Bump version number
      working-directory: MatchDungeon
      run: ./gradlew :android:incrementVersion

    - name: Build it
      working-directory: MatchDungeon
      run: |
        ./gradlew :headless:compileResources
        ./gradlew :android:bundleRelease

    - name: Setup git credentials
      working-directory: MatchDungeon
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "ReleaseToPlaystoreAction"

    - name: Release to playstore
      working-directory: MatchDungeon
      run: ./gradlew :headless:releaseAndroidToPlaystore
      id: release

    - name: Commit changes
      working-directory: MatchDungeon
      run: |
        git commit -m"Bump version number to steps.release.outputs.version and release" -a
        git tag -a releases/steps.release.outputs.version -m "Release steps.release.outputs.version"
      if: steps.release.outputs.status == 'Complete'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: MatchDungeon
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Push tags
      uses: ad-m/github-push-action@master
      with:
        directory: MatchDungeon
        tags: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
