name: ReleaseToPlaystore

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        path: MatchDungeon
        
    - name: Checkout submodules
      working-directory: MatchDungeon
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --rebase -j 8
    
    - name: Checkout private
      uses: actions/checkout@master
      with:
        repository: Lyeeedar/PrivateStuff
        token: ${{ secrets.PRIVATESTUFF_ACCESS_TOKEN }}
        path: PrivateStuff
        
    - name: Make gradlew executable
      working-directory: MatchDungeon
      run: chmod +x ./gradlew
    
    - name: Bump version number
      run: ./gradlew :android:incrementVersion
        
    - name: Build it
      working-directory: MatchDungeon
      run: |
        ./gradlew :headless:compileResources
        ./gradlew :android:bundleRelease
        
    - name: Release to playstore
      working-directory: MatchDungeon
      run: ./gradlew doRelease
        
    - name: Setup git credentials
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "ReleaseToPlaystoreAction"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
