name: Test

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
    - run: |
        git init /home/runner/work/MatchDungeon/MatchDungeon/MatchDungeon
        git remote add origin https://github.com/Lyeeedar/MatchDungeon
        git config --local gc.auto 0
        git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
        git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
        git fetch
        git checkout --progress --force -B master refs/remotes/origin/master
        
    - run: git tag
      working-directory: MatchDungeon
        
    - run: git describe --abbrev=0
      working-directory: MatchDungeon

    - run: git describe --tags
      working-directory: MatchDungeon



    - name: Checkout submodules
      working-directory: MatchDungeon
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --rebase -j 8
        
    - name: Checkout private
      uses: actions/checkout@master
      with:
        repository: Lyeeedar/PrivateStuff
        token: ${{ secrets.PRIVATESTUFF_ACCESS_TOKEN }}
        path: PrivateStuff

    - name: Make gradlew executable
      working-directory: MatchDungeon
      run: chmod +x ./gradlew

    - name: Bump version number
      working-directory: MatchDungeon
      run: ./gradlew :android:incrementVersion

    - name: Setup git credentials
      working-directory: MatchDungeon
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "testAction"
        
    - name: Commit changes
      working-directory: MatchDungeon
      run: git commit -m "test" -a
