name: UpgradeEngine

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        path: MatchDungeon
    
    - name: Checkout private
      uses: actions/checkout@master
      with:
        repository: Lyeeedar/PrivateStuff
        token: ${{ secrets.PRIVATESTUFF_ACCESS_TOKEN }}
        path: PrivateStuff
    
    - name: Update submodules
      working-directory: MatchDungeon
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --remote --rebase -j 8
        git submodule update --force --recursive --remote --rebase

    - name: Test it all builds
      working-directory: MatchDungeon
      run: |
        chmod +x ./gradlew
        ./gradlew :desktop:build
        ./gradlew :android:assembleDebug
        ./gradlew :headless:compileResources
        
    - name: Commit changes
      working-directory: MatchDungeon
      run: git commit -m "Upgrade engine" -a
      continue-on-error: true
        
    - name: Setup git credentials
      working-directory: MatchDungeon
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "ReleaseToPlaystoreAction"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: MatchDungeon
        github_token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
