name: UpgradeEngine

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: fregante/setup-git-token@v1
      with:
        name: EngineUpdaterAction
        email: actions@github.com
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --remote --rebase
        
    - name: Commit changes
      run: git commit -m "Upgrade engine" -a
        
    - name: Test it all builds
      if: success()
      run: |
        chmod +x ./gradlew
        ./gradlew :desktop:build
        ./gradlew :android:assembleDebug
        ./gradlew :headless:compileResources
        
    - name: Push changes
      run: git push
      continue-on-error: true
