name: UpgradeEngine

on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        path: Game

    - name: Checkout private
      uses: actions/checkout@master
      with:
        repository: Lyeeedar/PrivateStuff
        token: ${{ secrets.PRIVATESTUFF_ACCESS_TOKEN }}
        path: PrivateStuff

    - name: Update submodules
      working-directory: Game
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --remote --rebase -j 8
        git submodule update --force --recursive --remote --rebase

    - name: Setup git credentials
      working-directory: Game
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "UpgradeEngineAction"

    - name: Commit changes
      working-directory: Game
      run: |
        git commit -m "Upgrade engine" -a
        echo "::set-output name=status::Success"
      id: commit
      continue-on-error: true

    - name: Test it all builds
      working-directory: Game
      run: |
        chmod +x ./gradlew
        ./gradlew :headless:compileResources
        ./gradlew :desktop:build
        ./gradlew :android:assembleDebug
        ./gradlew :headless:testResources
      if: steps.commit.outputs.status == 'Success'

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: crashedLevelReplay
        path: Game/android/assets/crashedLevelReplay

    - name: Run Game Loop Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        script: ./Game/gradlew -p Game :headless:gameLoopTest
      if: steps.commit.outputs.status == 'Success'

    - name: Push changes
      uses: ad-m/github-push-action@master
      if: steps.commit.outputs.status == 'Success'
      with:
        directory: Game
        github_token: ${{ secrets.GITHUB_TOKEN }}